### ISSUE TITLE
Question: Is there a way to use starlark configuration files from Python?

### ISSUE THREAD

**Issue by indigoviolet** [bazelbuild/starlark#104]
I found the Go/Java/Rust implementations, but not a Python module.

If there isn't one, I was wondering how it could be put together easily:

It seems like it would be possible to import these files using a strategy similar to https://github.com/phgn0/pylint-starlark-plugin (transforming load to import), but that doesn't enforce the various guarantees/checking that Starlark provides.

I guess that in addition to the above transform, you could subprocess.run the starlark file(s) through (for ex.) the go-starlark executable, and use that, not sure if that is sufficient.

**Comment by alandonovan** [comment]
There is no Python port of Starlark. On the face of it, it might seem to be the most natural language in which to build an implementation, but it's actually quite a challenge. You can't re-use the existing data types of Python (bool, int, string, tuple, list, dict, etc) even though they are very similar, because they have different methods, and even corresponding methods behave differently (e.g. due to the freeze operation). You would have to define wrappers in Python, or for efficiency, implement them anew as C data types. It should be possible to compile Starlark functions to CPython bytecodes, so at least you don't need to reimplement the entire interpreter.
