### ISSUE TITLE
Python bindings for starlark-go

### ISSUE THREAD

**Issue by ColdHeat** [bazelbuild/starlark#137]
Hello! I spent some time writing Python bindings for starlark-go: https://github.com/ColdHeat/pystarlark. Just sharing in case it can be listed in the next update of the list of users. I have a separate even more experimental project planned but I imagine the most useful thing to most would be the Python bindings.

**Comment by alandonovan** [comment]
Nice!

BTW, you should call the `read` method `exec`, since it executes a file for its side effects.

I think the "users" list on this site should list applications that expose Starlark in their user interface, rather than libraries for working with Starlark. There are a couple of items that I ought to remove.

**Comment by ColdHeat** [comment]
Thanks for the tip! Can you elaborate a little though? ExecFile seemed like the simplest way to run a starlark script in starlark-go. Or do you mean from the Python side?

**Comment by alandonovan** [comment]
I meant that that Python method that wraps starlark.ExecFile should be called Exec or ExecFile too. "Read" means 'get bytes from a file', and this function does much more than that.

I notice the implementation also uses global variables in a way that is not thread-safe, and exposes raw C pointers as Python integers, when these should be encapsulated: ideally the lifetimes of Go variables would be tied to Python references using Python's finalization mechanism so that the user needn't call destroy.

**Comment by ColdHeat** [comment]
Ah gotcha now! 

I settled on this approach because there doesn't seem to be a way to pass non primitive types between Go and Python. Probably for good reason. 

As for thread safety, I only did some cursory research on whether it would be an issue since I believe the GIL would protect multiple Starlark threads from running at the same but I'm not 100% sure. Thank you for the advice though, I'll dig into it in the next few versions of pystarlark.

**Comment by alandonovan** [comment]
> there doesn't seem to be a way to pass non primitive types between Go and Python.

Even if there isn't a way, you shouldn't expose raw pointers as ints in your API as clients can fake them and cause you to write to (say) arbitrary memory. The int should be encapsulated so that clients can't see it.

> As for thread safety, I only did some cursory research on whether it would be an issue since I believe the GIL would protect multiple Starlark threads from running at the same

The GIL protects you from certain kinds of data race in Python itself (in CPython---not every implementation of Python even has a GIL) but it won't stop two Python threads executing Go code from concurrently accessing the same data (e.g. the global maps), nor does it prevent higher-level nonatomicity problems in code such as `x = get(); modify(x); set(x)`.
