### ISSUE TITLE
Starlark in Python?

### ISSUE THREAD

**Issue by suganoi** [bazelbuild/starlark#265]
Now we got Java, Go, and Java for Starlark. What about Python version?

**Comment by brandjon** [comment]
Feel free to write one. ;)

If you wanted to have a Starlark-in-Python implementation, I guess the first design issue is how you'd represent Starlark values internally. Would they be boxed inside some StarlarkValue class, or would they just be the underlying equivalent Python values, possibly with extra attributes added for tracking Starlark information like frozen-ness? After that you'd have to write (or generate) the parser, presumably an AST-based evaluator, etc.

You could also try to just execute Starlark code directly as Python, and in fact we do that for some of our tooling. But it's very brittle in exactly the ways you'd expect, so that doesn't really count as an implementation.

I'll close this since there's no real action item for this repo, which is concerned only with the language specification itself.

**Comment by laurentlb** [comment]
You can take a look at:
- https://github.com/caketop/python-starlark-go
- https://github.com/inducer/starlark-pyo3
