### ISSUE TITLE
hash definition

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/starlark#36]
Rust implementation:

```
$ target/debug/starlark-repl -c 'print(hash("ab"))'
7391266126405785627
```

Java implementation:

```
$ bazel run :Starlark -- -c 'print(hash("ab"))'
3105
```

Go implementation:

```
$ starlark -c 'print(hash("ab"))'
2230358275
```

For the Java implementation, the behavior is documented here: https://docs.bazel.build/versions/master/skylark/lib/globals.html#hash

Should other implementations use the same definition?

**Comment by dgryski** [comment]
I vote "no", because Java's string hashing function is poor quality and also limits optimization opportunities being required to process it a single character at a time.

**Comment by josharian** [comment]
There’s related discussion in https://github.com/google/starlark-go/issues/162#issuecomment-468826133

**Comment by alandonovan** [comment]
The spec now states the precise function used by `hash(str)`, and the Go and Java implementations agree on it. It's defined in terms of Java's String.hashCode, which as @dgryski says, is poor quality, but there's actually no requirement for the Starlark `hash` function be the same as the one used by String.hashCode or by Starlark's dict when inserting a string---the latter is an unobservable implementation detail. (And in the Go impl, they are not the same.)

The `hash` function is not used very much, so I don't know how important it is that we specify a more efficient one. The important thing is that we have convergence. (This turned out to be very important in a Go program I wrote that tsimulated Bazel:  the Go hash function differed, causing it to make different arbitrary choices, and sometimes crash due to latent bugs not exposed by the Java hash function.)

**Comment by adonovan** [comment]
I would be sympathetic to adding a sha256(string) function to the core language.
