### ISSUE TITLE
spec: allow assignment to empty tuple/list

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/starlark#93]
Consider an assignment whose left-hand side is an empty tuple () or list [].

Python2 statically disallows () but allows [].
Python3 allows both.
Starlark in Go statically disallows both.
Starlark in Java dynamically disallows both.

What should the spec say?

I argue that the Python3 behavior is correct. It is simple, obvious, and consistent. It is even potentially useful. For example, () = x is a quick way to assert that x is an empty sequence. Another example: a code generator that emits a statement (v1, ..., vn) = x would need extra logic for the n = 0 case.

I propose that we remove the special treatment of an empty list/tuple.

@brandjon @laurentlb

**Comment by ndmitchell** [comment]
This definition makes sense to me. I find the treatment of an empty list as being meaningfully different from the 1 element list as odd - they are approximately inductive data structures, so zero should just follow the pattern.

**Comment by laurentlb** [comment]
In the past, we decided to disallow `()` for compatibility with Python 2 (and disallow `[]` for consistency).
At the same time, I don't see much value in allowing them. If it happens in the code, it's probably a mistake (or an assert that has been disguised). The goal of the `=` statement is to define symbols, so the empty list doesn't make much sense here.

**Comment by ndmitchell** [comment]
I have three reasons for allowing them:

1. It's more like Python3. And by default I think Starlark should be like Python3 where there are choices to be made.
2. It makes for a shorter spec. Specifically one sentence shorter.
3. It's inductive. It works for 3. It works for 2. It works for 1. Why is 1 the base case and not zero? I wrote up some thoughts about this and how a lot of API's get it wrong: https://neilmitchell.blogspot.com/2011/02/corner-cases-and-zero-and-how-winforms.html

I agree, it probably isn't practically useful. But to me, the whole purpose of a spec is about nailing down all the corners that aren't practically useful, since every program will inadvertently wander in to one or two of them, and the spec is what makes things interoperate.

**Comment by alandonovan** [comment]
> I don't see much value in allowing them.

Laurent, my second example showed how complexity begets complexity.

> It's inductive. It works for 3. It works for 2. It works for 1. Why is 1 the base case and not zero? I wrote up some thoughts about this and how a lot of API's get it wrong: https://neilmitchell.blogspot.com/2011/02/corner-cases-and-zero-and-how-winforms.html

Yesterday I wrote some C++ to print a stringview using `printf("%*s", sv.size(), sv.data())`, and got a nasty surprise: if the size is zero, %*s doesn't print nothing, but instead behaves like %s and keeps printing until it reaches NUL. I don't know why anyone would do such a thing. The designers of Go's fmt.Printf fortunately didn't reproduce this bug.
